services:
  service-a:
    build: ../services/service-a
    container_name: service-a
    ports:
      - "8000:8000"
    environment:
      SERVICE_B_URL: http://service-b:8000
      FAIL_RATE: 0.1
      LATENCY_MS: 200
      OTEL_RESOURCE_ATTRIBUTES: service.name=service-a
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_LOG_LEVEL: debug
    depends_on:
      - service-b
      - otel-collector

  service-b:
    build: ../services/service-b
    container_name: service-b
    environment:
      SERVICE_C_URL: http://service-c:8000
      FAIL_RATE: 0.1
      LATENCY_MS: 300
      OTEL_RESOURCE_ATTRIBUTES: service.name=service-b
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_LOG_LEVEL: debug
    depends_on:
      - service-c
      - otel-collector

  service-c:
    build: ../services/service-c
    container_name: service-c
    environment:
      FAIL_RATE: 0.05
      LATENCY_MS: 100
      OTEL_RESOURCE_ATTRIBUTES: service.name=service-c
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_LOG_LEVEL: debug
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI